### ISSUE TITLE
[Request] CasparCG Module should be able to parse the rundown xml you create in CasparCG Client, so you can have your rundown with all single elements and groups as button presets in companion. 

### ISSUE THREAD

**Issue by badsen** [bitfocus/companion-module-casparcg#4] opened 2019-06-03 09:19 UTC
**Describe the feature**
The CasparCG Module should be able to parse the rundown xml you create in CasparCG Client, so you can have your rundown with all single elements and groups as button presets in companion. 

Ultra bonus would be if it automatically updates on changes on the xml.

**Is this platform dependent (windows, mac, ..)?**
no.

**If documentation is required to implement, do you know where to find it?**
If applicable, add screenshots, protocol description PDFs, etc to help the developers along

**Usecases**
This would enable Streamdeck and CasparCG to be an amazing Playout Engine and improves usiability a lot. The Problem with CasparCG and Companion right now is the System of CasparCG. 

CasparCG Server does not store the rundown. Usually you would want to edit your Rundown in the client and then have buttons for what you created. Right now you would have to reprogramm everything you did in CasparCG Client again for Companion.

**Comment by haakonnessjoen** [comment] 2019-12-09 07:35
This is now a duplicate of #3

**Closed by haakonnessjoen** 2019-12-09 07:35 UTC
